export const curatedLists = {
  blind75: [
    {
      id: "two-sum",
      title: "Two Sum",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/two-sum/",
    },
    {
      id: "best-time-to-buy-and-sell-stock",
      title: "Best Time to Buy and Sell Stock",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    },
    {
      id: "contains-duplicate",
      title: "Contains Duplicate",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/contains-duplicate/",
    },
    {
      id: "product-of-array-except-self",
      title: "Product of Array Except Self",
      difficulty: "Medium",
      topic: "Array",
      url: "https://leetcode.com/problems/product-of-array-except-self/",
    },
    {
      id: "maximum-subarray",
      title: "Maximum Subarray",
      difficulty: "Medium",
      topic: "Array",
      url: "https://leetcode.com/problems/maximum-subarray/",
    },
    {
      id: "maximum-product-subarray",
      title: "Maximum Product Subarray",
      difficulty: "Medium",
      topic: "Array",
      url: "https://leetcode.com/problems/maximum-product-subarray/",
    },
    {
      id: "find-minimum-in-rotated-sorted-array",
      title: "Find Minimum in Rotated Sorted Array",
      difficulty: "Medium",
      topic: "Array",
      url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    },
    {
      id: "search-in-rotated-sorted-array",
      title: "Search in Rotated Sorted Array",
      difficulty: "Medium",
      topic: "Array",
      url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    },
    {
      id: "3sum",
      title: "3Sum",
      difficulty: "Medium",
      topic: "Array",
      url: "https://leetcode.com/problems/3sum/",
    },
    {
      id: "container-with-most-water",
      title: "Container With Most Water",
      difficulty: "Medium",
      topic: "Array",
      url: "https://leetcode.com/problems/container-with-most-water/",
    },
    {
      id: "valid-anagram",
      title: "Valid Anagram",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/valid-anagram/",
    },
    {
      id: "group-anagrams",
      title: "Group Anagrams",
      difficulty: "Medium",
      topic: "String",
      url: "https://leetcode.com/problems/group-anagrams/",
    },
    {
      id: "valid-parentheses",
      title: "Valid Parentheses",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/valid-parentheses/",
    },
    {
      id: "valid-palindrome",
      title: "Valid Palindrome",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/valid-palindrome/",
    },
    {
      id: "longest-substring-without-repeating-characters",
      title: "Longest Substring Without Repeating Characters",
      difficulty: "Medium",
      topic: "String",
      url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    },
    {
      id: "reverse-linked-list",
      title: "Reverse Linked List",
      difficulty: "Easy",
      topic: "Linked List",
      url: "https://leetcode.com/problems/reverse-linked-list/",
    },
    {
      id: "climbing-stairs",
      title: "Climbing Stairs",
      difficulty: "Easy",
      topic: "Dynamic Programming",
      url: "https://leetcode.com/problems/climbing-stairs/",
    },
    {
      id: "min-stack",
      title: "Min Stack",
      difficulty: "Medium",
      topic: "Stack",
      url: "https://leetcode.com/problems/min-stack/",
    },
  ],
  neetcode150: [
    // Include all Blind 75 plus additional problems
    {
      id: "two-sum",
      title: "Two Sum",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/two-sum/",
    },
    {
      id: "contains-duplicate",
      title: "Contains Duplicate",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/contains-duplicate/",
    },
    {
      id: "valid-anagram",
      title: "Valid Anagram",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/valid-anagram/",
    },
    {
      id: "concatenation-of-array",
      title: "Concatenation of Array",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/concatenation-of-array/",
    },
    {
      id: "replace-elements-with-greatest-element-on-right-side",
      title: "Replace Elements with Greatest Element on Right Side",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/replace-elements-with-greatest-element-on-right-side/",
    },
    {
      id: "is-subsequence",
      title: "Is Subsequence",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/is-subsequence/",
    },
    {
      id: "length-of-last-word",
      title: "Length of Last Word",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/length-of-last-word/",
    },
    {
      id: "longest-common-prefix",
      title: "Longest Common Prefix",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/longest-common-prefix/",
    },
    {
      id: "pascal-triangle",
      title: "Pascal's Triangle",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/pascals-triangle/",
    },
    {
      id: "remove-duplicates-from-sorted-array",
      title: "Remove Duplicates from Sorted Array",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    },
    {
      id: "valid-sudoku",
      title: "Valid Sudoku",
      difficulty: "Medium",
      topic: "Hash Table",
      url: "https://leetcode.com/problems/valid-sudoku/",
    },
    {
      id: "word-search",
      title: "Word Search",
      difficulty: "Medium",
      topic: "Backtracking",
      url: "https://leetcode.com/problems/word-search/",
    },
    {
      id: "course-schedule",
      title: "Course Schedule",
      difficulty: "Medium",
      topic: "Graph",
      url: "https://leetcode.com/problems/course-schedule/",
    },
  ],
  grind75: [
    // Similar structure with Grind 75 problems
    {
      id: "two-sum",
      title: "Two Sum",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/two-sum/",
    },
    {
      id: "valid-parentheses",
      title: "Valid Parentheses",
      difficulty: "Easy",
      topic: "Stack",
      url: "https://leetcode.com/problems/valid-parentheses/",
    },
    {
      id: "merge-two-sorted-lists",
      title: "Merge Two Sorted Lists",
      difficulty: "Easy",
      topic: "Linked List",
      url: "https://leetcode.com/problems/merge-two-sorted-lists/",
    },
    {
      id: "best-time-to-buy-and-sell-stock",
      title: "Best Time to Buy and Sell Stock",
      difficulty: "Easy",
      topic: "Array",
      url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    },
    {
      id: "valid-palindrome",
      title: "Valid Palindrome",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/valid-palindrome/",
    },
    {
      id: "invert-binary-tree",
      title: "Invert Binary Tree",
      difficulty: "Easy",
      topic: "Tree",
      url: "https://leetcode.com/problems/invert-binary-tree/",
    },
    {
      id: "valid-anagram",
      title: "Valid Anagram",
      difficulty: "Easy",
      topic: "String",
      url: "https://leetcode.com/problems/valid-anagram/",
    },
    {
      id: "binary-search",
      title: "Binary Search",
      difficulty: "Easy",
      topic: "Binary Search",
      url: "https://leetcode.com/problems/binary-search/",
    },
    {
      id: "flood-fill",
      title: "Flood Fill",
      difficulty: "Easy",
      topic: "Graph",
      url: "https://leetcode.com/problems/flood-fill/",
    },
    {
      id: "lowest-common-ancestor-of-a-binary-search-tree",
      title: "Lowest Common Ancestor of a Binary Search Tree",
      difficulty: "Medium",
      topic: "Tree",
      url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    },
    {
      id: "maximum-depth-of-binary-tree",
      title: "Maximum Depth of Binary Tree",
      difficulty: "Easy",
      topic: "Tree",
      url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    },
    {
      id: "number-of-islands",
      title: "Number of Islands",
      difficulty: "Medium",
      topic: "Graph",
      url: "https://leetcode.com/problems/number-of-islands/",
    },
    {
      id: "implement-trie",
      title: "Implement Trie (Prefix Tree)",
      difficulty: "Medium",
      topic: "Trie",
      url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    },
  ],
};
